# config.yaml
simulation:
  grid_size: 50
  cell_size: 12
  simulation_speed: 0.1
terrain:
  preset: "valley"
  contact_radius: 1.0
automaton_rules:
  survival_threshold: [2, 3]
  birth_threshold: [3]
  enemy_tolerance: 3
teams:
  1:
    initial_pop_percent: 0.2
    health: 1
  2:
    initial_pop_percent: 0.2
    health: 1
visualization:
  colors:
    team1: [255, 0, 0]
    team2: [0, 0, 255]
victory:
  conquest_percentage: 70.0